<?php
/**
 * Created by PhpStorm.
 * User: xunuo
 * Date: 2017/6/29
 * Time: 14:12
 */

namespace app\api\controller;


class Index extends Common
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

    }
}